#!/usr/bin/env bun

import path from 'node:path';
import { $ } from 'bun';

const cliDir = path.resolve(import.meta.dirname, '..');
const webDir = path.resolve(cliDir, '..', 'web');
const distDir = path.resolve(webDir, 'dist');
const outFile = path.resolve(cliDir, 'dist', 'foyer');

process.chdir(cliDir);

console.log('Building web UI...');
await $`bun run --cwd ${webDir} build`;

const files = (
  await Array.fromAsync(new Bun.Glob('**/*').scan({ cwd: distDir }))
)
  .map((file) => file.replaceAll('\\', '/'))
  .sort();

const imports = files.map((file, i) => {
  const spec = path
    .relative(cliDir, path.join(distDir, file))
    .replaceAll('\\', '/');
  return `import file_${i} from ${JSON.stringify(spec.startsWith('.') ? spec : `./${spec}`)} with { type: 'file' };`;
});

const entries = files.map((file, i) => `  ${JSON.stringify(file)}: file_${i},`);

const generated = [
  '// Auto-generated by scripts/build.ts',
  ...imports,
  'export default {',
  ...entries,
  '}',
].join('\n');

console.log('Building CLI binary...');
const result = await Bun.build({
  entrypoints: [path.resolve(cliDir, 'bin', 'foyer.ts'), 'web-ui.gen.ts'],
  files: { 'web-ui.gen.ts': generated },
  compile: {
    target: `bun-${process.platform}-${process.arch}`,
    outfile: outFile,
  },
});

if (!result.success) {
  for (const log of result.logs) {
    console.error(log);
  }
  process.exit(1);
}

console.log(`Binary written to ${outFile}`);
